services:
  seerr:
    image: ghcr.io/fallenbagel/jellyseerr:latest
    init: true
    container_name: hp-seerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Africa/Johannesburg
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - hp-seerr:/app/config
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/status || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Seerr
      - flame.url=http://seerr.labuschagne.xyz
      - flame.icon=movie-open

volumes:
  hp-seerr:
    external: false
