services:
  web:
    container_name: hp-web
    build: .
    volumes:
      - ./conf:/etc/caddy/
      - hp-web-data:/data
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    networks:
      - hp-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  hp-web-data:
    external: false
