services:
  web:
    container_name: hp-web
    build: .
    volumes:
      - ./conf:/etc/caddy/
      - hp-web-data:/data
    ports:
      - 80:80
      - 443:443
      - 8000:8000
    networks:
      - hp-network
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M

volumes:
  hp-web-data:
    external: false
