services:
  mongo-6:
    image: mongo:6.0.21-jammy
    container_name: hp-mongo-6
    volumes:
      - hp-mongo-6-data:/data/db
    restart: unless-stopped
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  hp-mongo-6-data:
    external: false
