name: pg17

services:
  postgres-17:
    image: postgres:17.6-alpine3.21
    container_name: hp-postgres-17
    restart: always
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    healthcheck:
      test:
        - CMD
        - pg_isready
        - '-q'
        - '-d'
        - '${DB_DATABASE}'
        - '-U'
        - '${DB_USERNAME}'
      retries: 3
      timeout: 5s
    volumes:
      - 'hp-postgres-17-data:/var/lib/postgresql/data'
    networks:
      - hp-network
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1024M

volumes:
  hp-postgres-17-data:
    external: false
