services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:v3.4.1
    container_name: hp-flaresolverr
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
