services:
  server:
    image: ghcr.io/goauthentik/server:2025.8.3
    container_name: hp-authentik-server
    command: server
    env_file:
    - .env
    depends_on:
      hp-postgres-15:
        condition: service_healthy
      hp-redis-7:
        condition: service_healthy
    restart: unless-stopped
    volumes:
    - ./media:/media
    - ./templates:/templates

  worker:
    image: ghcr.io/goauthentik/server:2025.8.3
    container_name: hp-authentik-worker
    command: worker
    env_file:
    - .env
    depends_on:
      hp-postgres-15:
        condition: service_healthy
      hp-redis-7:
        condition: service_healthy
    restart: unless-stopped
    user: root
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./media:/media
    - ./certs:/certs
    - ./templates:/templates
