services:
  authentik-server:
    image: ghcr.io/goauthentik/server:2025.8.3
    container_name: hp-authentik-server
    command: server
    env_file:
      - .env
    depends_on:
      postgres-17:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hp-network
    volumes:
      - ./media:/media
      - ./templates:/templates
    labels:
      - flame.type=application
      - flame.name=Authentik
      - flame.url=https://auth.labuschagne.xyz
      - flame.icon=shield-lock
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M

  authentik-worker:
    image: ghcr.io/goauthentik/server:2025.8.3
    container_name: hp-authentik-worker
    command: worker
    env_file:
      - .env
    depends_on:
      postgres-17:
        condition: service_healthy
    restart: unless-stopped
    user: root
    networks:
      - hp-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./media:/media
      - ./certs:/certs
      - ./templates:/templates
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M
