services:
  pgadmin:
    container_name: hp-pgadmin
    image: dpage/pgadmin4:9.4.0
    restart: unless-stopped
    env_file:
      - environment/.env
    networks:
      - hp-network
    volumes:
      - hp-pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    labels:
      - flame.type=application
      - flame.name=Postgres Admin
      - flame.url=https://pgadmin.portal.tech
      - flame.icon=database-cog
