services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: hp-excalidraw
    restart: unless-stopped
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Excalidraw
      - flame.url=https://draw.labuschagne.xyz
      - flame.icon=draw
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
