services:
  your-spotify-client:
    image: yooooomi/your_spotify_client:1.14.0
    container_name: hp-your-spotify-client
    restart: unless-stopped
    env_file:
      - environment/.env
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Your Spotify
      - flame.url=https://spotify.portal.tech
      - flame.icon=spotify
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  your-spotify-server:
    image: yooooomi/your_spotify_server:1.14.0
    container_name: hp-your-spotify-server
    env_file:
      - environment/.env
    restart: unless-stopped
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
