services:
  mongo-6:
    image: mongo:6.0.21-jammy
    container_name: hp-mongo-6
    volumes:
      - hp-mongo-6-data:/data/db
    restart: unless-stopped
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  postgres-17:
    container_name: hp-postgres-17
    image: postgres:17.5-alpine3.22
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
    env_file:
      - environment/.env
    networks:
      - hp-network
    volumes:
      - hp-postgres-17-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  hp-mongo-6-data:
    external: false
  hp-postgres-17-data:
    external: false
