services:
  shopping-admin:
    container_name: hp-shopping-admin
    build:
      # Temporary fix for CSRF_TRUSTED_ORIGINS
      context: .
      dockerfile: temp/admin/Dockerfile
    env_file:
      - environment/.env
    networks:
      - hp-network
    depends_on:
      postgres-17:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    labels:
      - flame.type=application
      - flame.name=Shopping Admin
      - flame.url=https://shopping.portal.tech/admin/
      - flame.icon=account-group

  shopping-app:
    container_name: hp-shopping-app
    build:
      # Temporary fix for CSRF_TRUSTED_ORIGINS
      context: .
      dockerfile: temp/app/Dockerfile
    env_file:
      - environment/.env
    environment:
      - GUNICORN_WORKERS=1
    networks:
      - hp-network
    depends_on:
      postgres-17:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    labels:
      - flame.type=application
      - flame.name=Shopping App
      - flame.url=https://shopping.portal.tech
      - flame.icon=cart
