services:
  redis-8:
    image: redis:8.0.2-alpine3.21
    container_name: hp-redis-8
    volumes:
      - hp-redis-8-data:/data
    networks:
      - hp-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
