services:
  shopping-admin:
    container_name: hp-shopping-admin
    build:
      # Temporary fix for CSRF_TRUSTED_ORIGINS
      context: .
      dockerfile: admin/Dockerfile
    env_file:
      - .env
    networks:
      - hp-network
    depends_on:
      postgres-16:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    labels:
      - flame.type=application
      - flame.name=Shopping Admin
      - flame.url=https://shopping.labuschagne.xyz/admin/
      - flame.icon=account-group

  shopping-app:
    container_name: hp-shopping-app
    build:
      # Temporary fix for CSRF_TRUSTED_ORIGINS
      context: .
      dockerfile: app/Dockerfile
    env_file:
      - .env
    environment:
      - GUNICORN_WORKERS=1
    networks:
      - hp-network
    depends_on:
      postgres-16:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1024M
    labels:
      - flame.type=application
      - flame.name=Shopping App
      - flame.url=https://shopping.labuschagne.xyz
      - flame.icon=cart
