services:
  pgadmin:
    container_name: hp-pgadmin
    image: dpage/pgadmin4:9.8.0
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PGADMIN_CONFIG_PROXY_X_FOR_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_PROTO_COUNT=1
      - PGADMIN_CONFIG_PROXY_X_HOST_COUNT=1
    networks:
      - hp-network
    volumes:
      - hp-pgadmin-data:/var/lib/pgadmin
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    labels:
      - flame.type=application
      - flame.name=Postgres Admin
      - flame.url=https://pgadmin.labuschagne.xyz
      - flame.icon=database-cog

volumes:
  hp-pgadmin-data:
    external: false
