services:
  actual-server:
    image: docker.io/actualbudget/actual-server:latest
    container_name: hp-actual-server
    volumes:
      - hp-actual-data:/data
    healthcheck:
      test: [ 'CMD-SHELL', 'node src/scripts/health-check.js' ]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped
    networks:
      - hp-network
    labels:
      - flame.type=application
      - flame.name=Actual Budget
      - flame.url=https://budget.labuschagne.xyz
      - flame.icon=cash-multiple
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
  hp-actual-data:
    external: false
