services:
  byparr:
    image: ghcr.io/thephaseless/byparr:2.0.1
    container_name: hp-byparr
    restart: unless-stopped
    init: true
    ports:
      - "8191:8191"
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
