services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: hp-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
    restart: unless-stopped
    networks:
      - hp-network
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: hp-qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - ${TORRENT_DOWNLOADS_PATH:-./downloads}:/downloads
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 4096M
    labels:
      - flame.type=application
      - flame.name=qBittorrent
      - flame.url=http://torrent.labuschagne.xyz
      - flame.icon=download

volumes:
  gluetun-data:
    external: false
  qbittorrent-config:
    external: false
