services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: hp-gluetun
    ports:
      - "8080:8080"
      - "8191:8191"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - gluetun-data:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - VPN_PORT_FORWARDING=on
      - PORT_FORWARD_ONLY=on
      - DOT=off
      - DNS_ADDRESS=1.1.1.1
    restart: unless-stopped
    networks:
      - hp-network
    logging: *default-logging
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: hp-qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent-config:/config
      - ${TORRENT_DOWNLOADS_PATH:-./downloads}:/downloads
      - /tmp/gluetun/forwarded_port:/tmp/gluetun/forwarded_port:ro
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '8.0'
          memory: 4096M
    labels:
      - flame.type=application
      - flame.name=qBittorrent
      - flame.url=http://torrent.labuschagne.xyz
      - flame.icon=download

  byparr:
    image: ghcr.io/thephaseless/byparr:2.0.1
    container_name: hp-byparr
    restart: unless-stopped
    init: true
    network_mode: "service:gluetun"
    depends_on:
      - gluetun
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2048M

volumes:
  gluetun-data:
    external: false
  qbittorrent-config:
    external: false
