services:
  redis-7:
    image: redis:7.4.5-alpine3.21
    container_name: hp-redis-7
    restart: unless-stopped
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    volumes:
      - hp-redis-7-data:/data
    networks:
      - hp-network

volumes:
  hp-redis-7-data:
    external: false
